---
- name: Add golang plugin to asdf
  command: "asdf plugin-add golang"
  register: golang_add
  failed_when: golang_add == 2

- name: Install golang {{golang_version}} with asdf
  command: "asdf install golang {{golang_version}}"

- name: Set global version for golang to {{golang_version}}
  command: "asdf global golang {{golang_version}}"
