---
- name: Add python plugin for asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add python"
  register: python_add
  failed_when: python_add == 1

- name: "Install python3 {{python3_version}} with asdf"
  command: "${HOME}/.asdf/bin/asdf install python {{python3_version}}"

- name: "Install python2 {{python2_version}} with asdf"
  command: "${HOME}/.asdf/bin/asdf install python {{python2_version}}"

- name: Set global versions for python
  command: "${HOME}/.asdf/bin/asdf global python {{python3_version}} {{python2_version}}"

- name: Check if pytest.ini file exists
  stat: path="{{dotfiles_user_home}}/pytest.ini"
  register: pytest_stat

- name: Back up pytest.ini file
  command: "mv ${HOME}/pytest.ini ${HOME}/pytest.ini.bak"
  args:
    creates: "{{dotfiles_user_home}}/pytest.ini"
  when: pytest_stat.stat.exists

- name: Link pytest.ini file
  file:
    src: "{{dotfiles_home}}/roles/python/files/pytest.ini"
    dest: "{{dotfiles_user_home}}/pytest.ini"
    state: link

- name: Install pipx
  tags: pipx
  shell: "python3 -m pip install --user pipx && PYENV_VERSION=system python3 -m pipx install pipx"
  args:
    creates: "{{dotfiles_user_home}}/.local/bin/pipx"
