---
- name: Clone asdf repository
  git:
    repo: git@github.com:asdf-vm/asdf.git
    dest: "${HOME}/.asdf"
    version: v0.9.0

# - name: add ${HOME}/.asdf/bin to path
#   ansible.builtin.lineinfile:
#     dest: /etc/environment
#     state: present
#     backrefs: yes
#     regexp: 'PATH=(["]*)((?!.*?${HOME}/.asdf/bin).*?)(["]*)$'
#     line: 'PATH=\1\2:${HOME}/.asdf/bin\3'
#   become: true
#   become_user: root
#   become_method: sudo

