---
- name: Add nodejs plugin to asdf [https://github.com/asdf-vm/asdf-nodejs]
  command: "${HOME}/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
  register: node_add
  failed_when: node_add == 2

- name: Install nodejs {{node_version}} with asdf
  command: "${HOME}/.asdf/bin/asdf install nodejs {{node_version}}"

- name: Set global version for nodejs to {{node_version}}
  command: "${HOME}/.asdf/bin/asdf global nodejs {{node_version}}"

- name: Install "yarn" node.js package globally
  npm:
    name: yarn
    global: yes
